// flow-typed signature: 09f8f04ee0c2b98898704d678b7c3c94
// flow-typed version: <<STUB>>/bootswatch_v^4.0.0-beta.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootswatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootswatch' {
  declare module.exports: any;
}
